---
abstract: 'Pretty-print data structure for console output'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Data::Dump::Partial: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Format-Pretty-Console
requires:
  Data::Unixish: 1.34
  Data::Unixish::Apply: 1.33
  JSON: 0
  Log::Any: 0
  Text::ANSITable: 0.08
  YAML::Any: 0
  experimental: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Data-Format-Pretty-Console/
  repository: http://github.com/sharyanto/perl-Data-Format-Pretty-Console
version: 0.30
